"""feat: adiciona a tabela tb_orgao_financeiro

Revision ID: 05c95359d2b7
Revises: ac7fa30b9113
Create Date: 2025-08-27 10:49:58.811849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c95359d2b7'
down_revision: Union[str, Sequence[str], None] = 'ac7fa30b9113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_orgao_financeiro',
    sa.Column('id_orgao_financeiro', sa.Integer(), nullable=False),
    sa.Column('nr_cnpj', sa.String(length=14), nullable=False),
    sa.Column('nm_razao_social', sa.String(length=150), nullable=False),
    sa.Column('nm_fantasia', sa.String(length=150), nullable=False),
    sa.Column('fl_ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_orgao_financeiro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_orgao_financeiro')
    # ### end Alembic commands ###
