"""feat: adiciona a tabela tb_posicao

Revision ID: 3369a2c51e1a
Revises: 7ec88b879b87
Create Date: 2025-08-27 11:11:00.815978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3369a2c51e1a'
down_revision: Union[str, Sequence[str], None] = '7ec88b879b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tb_posicao',
        sa.Column('id_posicao', sa.Integer(), nullable=False),
        sa.Column('id_ativo', sa.Integer(), nullable=False),
        sa.Column('vl_pu_posicao', sa.Numeric(precision=24, scale=9), nullable=False),
        sa.Column('vl_principal', sa.Numeric(precision=24, scale=9), nullable=False),
        sa.Column('vl_financeiro_disponivel', sa.Numeric(precision=24, scale=9), nullable=False),
        sa.Column('dt_posicao', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['id_ativo'], ['tb_ativo.id_ativo'], ),
        sa.PrimaryKeyConstraint('id_posicao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_posicao')
    # ### end Alembic commands ###
