"""feat: adiciona a tabela tb_ativo

Revision ID: 7ec88b879b87
Revises: b299ad81b0c7
Create Date: 2025-08-27 11:06:50.399082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec88b879b87'
down_revision: Union[str, Sequence[str], None] = 'b299ad81b0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tb_ativo',
        sa.Column('id_ativo', sa.Integer(), nullable=False),
        sa.Column('id_fundo', sa.Integer(), nullable=True),
        sa.Column('id_lote', sa.Integer(), nullable=False),
        sa.Column('id_indexador', sa.Integer(), nullable=False),
        sa.Column('cd_ativo', sa.String(length=100), nullable=False),
        sa.Column('cd_isin', sa.String(length=100), nullable=False),
        sa.Column('nm_ativo', sa.String(length=100), nullable=False),
        sa.Column('tp_ativo', sa.String(length=100), nullable=False),
        sa.Column('vl_pu_emisssao', sa.Numeric(precision=24, scale=9), nullable=False),
        sa.Column('dt_emissao', sa.Date(), nullable=False),
        sa.Column('dt_vencimento', sa.Date(), nullable=False),
        sa.Column('fl_ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['id_fundo'], ['tb_fundo_investimento.id_fundo_investimento'], ),
        sa.ForeignKeyConstraint(['id_indexador'], ['tb_indexador.id_indexador'], ),
        sa.ForeignKeyConstraint(['id_lote'], ['tb_lote.id_lote'], ),
        sa.PrimaryKeyConstraint('id_ativo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_ativo')
    # ### end Alembic commands ###
