services:
  db:
    container_name: fundsys_db
    image: postgres:13.22
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    container_name: fundsys_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - ./app:/fundsys_project/app
      - ./main.py:/fundsys_project/main.py
      - ./logging_config.py:/fundsys_project/logging_config.py
      - ./alembic.ini:/fundsys_project/alembic.ini
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
