services:
  db:
    container_name: fundsys_db
    image: postgres:13.22
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    container_name: fundsys_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./logging_config.py:/app/logging_config.py
      - ./requirements.txt:/app/requirements.txt
      - ./venv:/app/venv
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
