"""feat: adiciona a tabela tb_relacao_ativo_securitizadora

Revision ID: 0093e3165017
Revises: 6141c3e62634
Create Date: 2025-08-27 21:35:23.174254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0093e3165017'
down_revision: Union[str, Sequence[str], None] = '6141c3e62634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tb_relacao_ativo_securitizadora',
        sa.Column('id_relacao_ativo_securitizadora', sa.Integer(), nullable=False),
        sa.Column('id_ativo', sa.Integer(), nullable=False),
        sa.Column('id_securitizadora', sa.Integer(), nullable=False),
        sa.Column('fl_relacao_ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['id_ativo'], ['tb_ativo.id_ativo'], ),
        sa.ForeignKeyConstraint(['id_securitizadora'], ['tb_securitizadora.id_securitizadora'], ),
        sa.PrimaryKeyConstraint('id_relacao_ativo_securitizadora')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_relacao_ativo_securitizadora')
    # ### end Alembic commands ###
