"""feat: adiciona tabela arquivo original

Revision ID: 0095e3165019
Revises: a451fe4e7049
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0095e3165019'
down_revision = 'a451fe4e7049'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_arquivo_original',
    sa.Column('id_arquivo_original', sa.Integer(), nullable=False),
    sa.Column('id_fundo_investimento', sa.Integer(), nullable=False),
    sa.Column('nm_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nm_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('conteudo_arquivo', sa.Text(), nullable=False),
    sa.Column('hash_arquivo', sa.String(length=64), nullable=False),
    sa.Column('tamanho_arquivo', sa.Integer(), nullable=False),
    sa.Column('fl_processado', sa.Boolean(), nullable=False),
    sa.Column('fl_erro_processamento', sa.Boolean(), nullable=False),
    sa.Column('ds_erro_processamento', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_fundo_investimento'], ['tb_fundo_investimento.id_fundo_investimento'], ),
    sa.PrimaryKeyConstraint('id_arquivo_original'),
    sa.UniqueConstraint('hash_arquivo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_arquivo_original')
    # ### end Alembic commands ###
