"""feat: adiciona tabela ativo_enriquecido

Revision ID: 0096e3165020
Revises: 0095e3165019
Create Date: 2025-09-12 10:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0096e3165020'
down_revision = '0095e3165019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_ativo_enriquecido',
    sa.Column('id_ativo_enriquecido', sa.Integer(), nullable=False),
    sa.Column('id_ativo', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=100), nullable=True),
    sa.Column('emissao', sa.String(length=100), nullable=True),
    sa.Column('devedor', sa.String(length=200), nullable=True),
    sa.Column('securitizadora', sa.String(length=200), nullable=True),
    sa.Column('resgate_antecipado', sa.String(length=50), nullable=True),
    sa.Column('agente_fiduciario', sa.String(length=200), nullable=True),
    sa.Column('fl_enriquecido', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('fl_erro_enriquecimento', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('ds_erro_enriquecimento', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_ativo'], ['tb_ativo.id_ativo'], ),
    sa.PrimaryKeyConstraint('id_ativo_enriquecido'),
    sa.UniqueConstraint('id_ativo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_ativo_enriquecido')
    # ### end Alembic commands ###

