"""adjust: remove duas colunas e adiciona outras duas:
- removidas: nm_ativo, tp_ativo
- adicionadas: pc_indexador, pc_cupom

Revision ID: 1f8530b2502b
Revises: 0093e3165017
Create Date: 2025-09-03 03:11:56.724122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8530b2502b'
down_revision: Union[str, Sequence[str], None] = '0093e3165017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_ativo', sa.Column('perc_indexador', sa.Float(), nullable=False))
    op.add_column('tb_ativo', sa.Column('perc_cupom', sa.Float(), nullable=False))
    op.drop_column('tb_ativo', 'nm_ativo')
    op.drop_column('tb_ativo', 'tp_ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_ativo', sa.Column('tp_ativo', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tb_ativo', sa.Column('nm_ativo', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('tb_ativo', 'perc_cupom')
    op.drop_column('tb_ativo', 'perc_indexador')
    # ### end Alembic commands ###
