"""feat: adiciona a tabela tb_fundo_financeiro

Revision ID: 21c3e900d26e
Revises: 05c95359d2b7
Create Date: 2025-08-27 10:53:13.597815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c3e900d26e'
down_revision: Union[str, Sequence[str], None] = '05c95359d2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_fundo_investimento',
    sa.Column('id_fundo_investimento', sa.Integer(), nullable=False),
    sa.Column('id_orgao_financeiro', sa.Integer(), nullable=True),
    sa.Column('nm_fundo_investimento', sa.String(length=100), nullable=False),
    sa.Column('ds_fundo_investimento', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_orgao_financeiro'], ['tb_orgao_financeiro.id_orgao_financeiro'], ),
    sa.PrimaryKeyConstraint('id_fundo_investimento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_fundo_investimento')
    # ### end Alembic commands ###
