"""feat: adiciona a tabela tb_securitizadora

Revision ID: 6141c3e62634
Revises: 3369a2c51e1a
Create Date: 2025-08-27 21:21:33.726649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6141c3e62634'
down_revision: Union[str, Sequence[str], None] = '3369a2c51e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_securitizadora',
        sa.Column('id_securitizadora', sa.Integer(), nullable=False),
        sa.Column('nr_cnpj', sa.String(length=14), nullable=False),
        sa.Column('nm_razao_social', sa.String(length=150), nullable=False),
        sa.Column('nm_fantasia', sa.String(length=150), nullable=False),
        sa.Column('fl_ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id_securitizadora'),
        sa.UniqueConstraint('nm_razao_social'),
        sa.UniqueConstraint('nr_cnpj')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_securitizadora')
    # ### end Alembic commands ###
