"""fix: transforma em optional e permitindo null a coluna sgl_indexador da tabela tb_indexador

Revision ID: a451fe4e7049
Revises: 1f8530b2502b
Create Date: 2025-09-10 12:01:23.962848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a451fe4e7049'
down_revision: Union[str, Sequence[str], None] = '1f8530b2502b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_indexador', 'sgl_indexador',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_indexador', 'sgl_indexador',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
