"""feat: adiciona a tabela tb_lote

Revision ID: ac7fa30b9113
Revises: be6eea32a93d
Create Date: 2025-08-27 09:10:19.027072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7fa30b9113'
down_revision: Union[str, Sequence[str], None] = 'be6eea32a93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_lote',
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('vl_pu_compra', sa.NUMERIC(24, 9), nullable=False),
    sa.Column('qtd_comprada', sa.NUMERIC(24, 9), nullable=False),
    sa.Column('dt_operacao', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_lote')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_lote')
    # ### end Alembic commands ###
