"""feat: adiciona a tabela tb_indexador

Revision ID: b299ad81b0c7
Revises: 21c3e900d26e
Create Date: 2025-08-27 11:02:27.773924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b299ad81b0c7'
down_revision: Union[str, Sequence[str], None] = '21c3e900d26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_indexador',
    sa.Column('id_indexador', sa.Integer(), nullable=False),
    sa.Column('cd_indexador', sa.String(length=100), nullable=False),
    sa.Column('sgl_indexador', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_indexador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_indexador')
    # ### end Alembic commands ###
